service: admin-api
app: mbm-backend
org: madebymaa

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-south-1
  profile: madebymaa-prod
  environment: 
    DB: "mongodb+srv://username:password@cluster0.random.mongodb.net/prod?retryWrites=true&w=majority"
    ADMIN_APP_DOMAIN: "https://dashboard.madebymaa.in"
    S3_BUCKET: "madebymaa-prod-images-bucket"


functions:
  api:
    handler: handler.router
    timeout: 30
    events:
      - http:
          path: 'api/v1/admin/'
          method: any
          cors: true
      - http:
          path: 'api/v1/admin/{proxy+}'
          method: any
          cors: true