module.exports = {
    ORDER_CREATED: 'ORDER_CREATED',
    AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
    RESTAUTANT_CONFIRMED: 'RESTAUTANT_CONFIRMED',
    RESTAURANT_DECLINED: 'RESTAURANT_DECLINED',
    ORDER_PREPARED: 'ORDER_PREPARED',
    AWAITING_DELIVERY_PARTNER: 'AWAITING_DELIVERY_PARTNER',
    PARTNER_CONFIRMED: 'PARTNER_CONFIRMED',
    ORDER_PICKED_UP: 'ORDER_PICKED_UP',
    ORDER_DELIVERED: 'ORDER_DELIVERED',
    ORDER_CANCELLED: 'ORDER_CANCELLED',
    enum: [
        'ORDER_CREATED',
        'AWAITING_CONFIRMATION',
        'RESTAUTANT_CONFIRMED',
        'RESTAURANT_DECLINED',
        'ORDER_PREPARED',
        'AWAITING_DELIVERY_PARTNER',
        'PARTNER_CONFIRMED',
        'ORDER_PICKED_UP',
        'ORDER_DELIVERED',
        'ORDER_CANCELLED'
    ]
};